# Generated by Django 5.2.5 on 2026-03-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrole',
            name='role_category',
            field=models.CharField(choices=[('admin', 'Admin'), ('owner', 'Owner')], default='customer', max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_category',
            field=models.CharField(choices=[('admin', 'Admin'), ('owner', 'Owner')], default='customer', max_length=100),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['owner'], name='restaurants_owner_i_229fd6_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['status'], name='restaurants_status_7a5ebb_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['restaurant'], name='subscriptio_restaur_8215e9_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='subscriptio_status_572d44_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['phone'], name='users_phone_af6883_idx'),
        ),
    ]
