# Generated by Django 5.2.5 on 2026-03-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_historicalrole_role_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalusers',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_staff',
        ),
    ]
