# Generated by Django 5.2.5 on 2026-03-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_historicalusers_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusers',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
