# Generated by Django 5.2.5 on 2026-03-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_historicalsubscriptionplan_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusers',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalusers',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalusers',
            name='otp_blocked_until',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalusers',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalusers',
            name='otp_last_sent_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='otp_blocked_until',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='otp_last_sent_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalusers',
            name='otp',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='otp',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
    ]
