# Generated by Django 5.2.5 on 2026-03-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_historicalusers_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusers',
            name='otp_context',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalusers',
            name='pending_email',
            field=models.EmailField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='otp_context',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='pending_email',
            field=models.EmailField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
