# Generated by Django 5.2.12 on 2026-04-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_stripewebhooklog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymenttransaction',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
