# Generated by Django 5.2.12 on 2026-04-08 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_historicalpaymenttransaction_transaction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2)),
                ('currency', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalpaymenttransaction',
            name='stripe_charge_id',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='stripe_charge_id',
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalpaymenttransaction',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='historicalrefund',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['currency'], name='payment_tra_currenc_22df81_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['country'], name='payment_tra_country_f9db97_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_id'], name='payment_tra_transac_4a22d3_idx'),
        ),
        migrations.AddField(
            model_name='planpricing',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='app.subscriptionplan'),
        ),
        migrations.AlterUniqueTogether(
            name='planpricing',
            unique_together={('plan', 'country')},
        ),
    ]
