# Generated by Django 5.2.12 on 2026-04-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_planpricing_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={},
        ),
        migrations.RemoveField(
            model_name='historicalsubscriptionplan',
            name='price',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='price',
        ),
    ]
