# Generated by Django 5.2.12 on 2026-04-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_subscription_unique_user_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubscriptionplan',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
