# Generated by Django 5.2.12 on 2026-04-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_historicalsubscriptionplan_stripe_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusers',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
