# Generated by Django 5.2.12 on 2026-05-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_historicalsubscription_cancel_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsubscriptionplan',
            old_name='stripe_product_id',
            new_name='stripe_product_id_live',
        ),
        migrations.RenameField(
            model_name='planpricing',
            old_name='stripe_price_id',
            new_name='stripe_price_id_live',
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='stripe_product_id',
            new_name='stripe_product_id_live',
        ),
        migrations.AlterUniqueTogether(
            name='planpricing',
            unique_together={('plan', 'country', 'currency')},
        ),
        migrations.AddField(
            model_name='historicalsubscriptionplan',
            name='stripe_product_id_test',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='planpricing',
            name='stripe_price_id_test',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_product_id_test',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='plan_interval',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalsubscriptionplan',
            name='interval',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='plan_interval',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='interval',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
    ]
